services:
  web:
    build: .
    environment:
      - DJANGO_SETTINGS_MODULE=bookstore.settings
      - DATABASE_URL=postgres://postgres:postgres@db:5432/bookstore
      - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY:-your-secret-key-here}
      - DJANGO_DEBUG=True
      - DJANGO_ALLOWED_HOSTS=localhost,127.0.0.1
    depends_on:
      - db
    ports:
      - "8000:8000"
    volumes:
      - type: bind
        source: .
        target: /app
      - static_volume:/app/static
      - media_volume:/app/media
    networks:
      - app_network

  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=bookstore
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    networks:
      - app_network

volumes:
  postgres_data:
  static_volume:
  media_volume:

networks:
  app_network:
  